version: '2'
services:
  messageapi:
    build:
      context: ./
      dockerfile: Dockerfile-Node
    command: "bash -c 'npm start'"
    volumes:
      - ./:/project
    links:
      - mongodb
    ports:
      - 3000:3000
    environment:
      - MESSAGE_API_MONGO_HOST=mongodb

  mongodb:
    image: mongo:3.4.7
    ports:
      - 27017:27017
